 #!/bin/bash
 evaluate.sh load_delay_1.asm memory.mem 
 evaluate.sh load_delay_2.asm memory.mem 
 evaluate.sh load_delay_3.asm memory.mem 
 evaluate.sh load_reg_1.asm memory.mem 
 evaluate.sh load_reg_2.asm memory.mem 
 evaluate.sh load_reg_3.asm memory.mem 
 evaluate.sh alu_reg_1.asm memory.mem 
 evaluate.sh alu_reg_2.asm memory.mem 
 evaluate.sh alu_reg_3.asm memory.mem 
 evaluate.sh ex-mem_to_ex_1.asm memory.mem 
 evaluate.sh ex-mem_to_ex_2.asm memory.mem 
 evaluate.sh ex-mem_to_ex_3.asm memory.mem 
 evaluate.sh mem-wb_to_ex_1.asm memory.mem 
 evaluate.sh mem-wb_to_ex_2.asm memory.mem 
 evaluate.sh mem-wb_to_ex_3.asm memory.mem 
 evaluate.sh mem-wb_to_ex_4.asm memory.mem 
 evaluate.sh mem-wb_to_ex_5.asm memory.mem 
 evaluate.sh mem-wb_to_ex_6.asm memory.mem 
 evaluate.sh st_mem-wb_mem.asm memory.mem 
 evaluate.sh st_addr_ex-mem_ex.asm memory.mem 
 evaluate.sh st_addr_mem-wb_ex.asm memory.mem 
 evaluate.sh ld_addr_mem-wb_ex.asm memory.mem 
 evaluate.sh ld_addr_ex-mem_ex.asm memory.mem 
 evaluate.sh ld_st_mem-wb_mem.asm memory.mem 
 evaluate.sh branch_1.asm memory.mem 
 evaluate.sh branch_2.asm memory.mem 
 evaluate.sh big_test.asm memory.mem 
